workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        ANDROID_KEYSTORE: ./key/key.jks
        ANDROID_KEYSTORE_PASSWORD: hesoyam
        ANDROID_KEY_ALIAS: key
        ANDROID_KEY_PASSWORD: hesoyam
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk